getwd()
rm(list=ls())  

vist<-read.csv("E:\\KJ\\Data Science\\neeraj hatekar sir\\Assignment 2\\visits.csv", header=T)
attach(vist)

dim(vist)
head(vist)
colnames(vist)
M<-ts(Total.Visits,start=c(2013,1),freq=365)
par(mfrow=c(2,1))
plot.ts(M)
#acf(M)
#pacf(M)
#adf.test(M)
M1<-diff(log(M))
plot.ts(M1)
#adf.test(M1)
#decompose(M1)
par(mfrow=c(2,1))
a<-acf(M1)
pa<-pacf(M1)
#day<-cbind("Tue","wed","thu","fri","sat","sun","mon")
#model1<-auto.arima(M1,xreg=day)
mod1<-arima(M1, order=c(4,0,2), seasonal=list(order=c(1,0,1),period=7))
mod1_auto<-auto.arima(M1)
summary(mod1)
plot(M1,col="red")
lines(fitted(mod1),col="blue")
plot(mod1)
## forcasting visits
F1<-forecast(mod1,h=7)
str(F1)
par(mfrow=c(1,1))

plot(F1)
